/**
 * Emit the app-side asset manifest from assets.json.
 *
 * Outputs:
 *   mobile/src/sanctuary/assetManifest.gen.ts  -- consumed by the 3D scene
 *   manifest.gen.json (next to this script)    -- consumed by validate.mjs
 *
 * The TS module maps:
 *   elements:  content icon key -> { module: require(glb), anchor, ... }
 *   scenery:   zone tier-dressing entries gated by tierMin
 *
 * Regenerate after editing assets.json; CI runs `git diff --exit-code` on
 * the generated TS so drift cannot merge (same trick as content/schema/).
 */

import { readFile, writeFile, stat } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const MOBILE_ASSETS = path.join(HERE, "..", "..", "mobile", "assets", "sanctuary", "models");
const TS_OUT = path.join(HERE, "..", "..", "mobile", "src", "sanctuary", "assetManifest.gen.ts");
const JSON_OUT = path.join(HERE, "manifest.gen.json");

const assetsConfig = JSON.parse(await readFile(path.join(HERE, "assets.json"), "utf8"));

const elements = [];
const scenery = [];

for (const entry of assetsConfig.entries) {
  if (entry.kind === "dev") continue; // dev/spike assets never enter the manifest
  const outPath = path.join(MOBILE_ASSETS, entry.out);
  try {
    await stat(outPath);
  } catch {
    console.error(`✗ ${entry.name}: missing GLB ${entry.out} -- run normalize.mjs first`);
    process.exitCode = 1;
    continue;
  }
  const common = {
    name: entry.name,
    out: entry.out,
    zone: entry.zone,
    anchor: entry.anchor ?? null,
    scale: entry.scale ?? 1,
    rotationY: entry.rotationY ?? 0,
    animations: entry.animations ?? [],
  };
  if (entry.kind === "element") {
    elements.push({ ...common, iconKey: entry.iconKey });
  } else if (entry.kind === "scenery") {
    scenery.push({ ...common, tierMin: entry.tierMin ?? 1 });
  }
}

elements.sort((a, b) => a.iconKey.localeCompare(b.iconKey));
scenery.sort((a, b) => a.name.localeCompare(b.name));

function requirePath(out) {
  return `require("../../assets/sanctuary/models/${out.replace(/\\/g, "/")}")`;
}

function tsEntry(entry, extra) {
  return [
    `  ${JSON.stringify(extra.key)}: {`,
    `    module: ${requirePath(entry.out)} as number,`,
    `    zone: ${JSON.stringify(entry.zone)},`,
    `    anchor: ${JSON.stringify(entry.anchor)},`,
    `    scale: ${entry.scale},`,
    `    rotationY: ${entry.rotationY},`,
    `    animations: ${JSON.stringify(entry.animations)},`,
    ...extra.lines,
    `  },`,
  ].join("\n");
}

const ts = `// AUTO-GENERATED by scripts/sanctuary_assets/build_manifest.mjs -- DO NOT EDIT.
// Source of truth: scripts/sanctuary_assets/assets.json
// Regenerate: cd scripts/sanctuary_assets && npm run manifest

import type { SanctuaryZoneId } from "@/src/api/sanctuary";

export type SanctuaryElementAsset = {
  /** Metro asset module id (the value of require("….glb")). */
  module: number;
  zone: SanctuaryZoneId | null;
  anchor: string | null;
  scale: number;
  rotationY: number;
  animations: readonly string[];
};

export type SanctuarySceneryAsset = SanctuaryElementAsset & {
  /** Renders once the zone's depth_tier reaches this threshold. */
  tierMin: number;
};

/** Content icon key (content/sanctuary/*.json) -> placed model. */
export const SANCTUARY_ELEMENT_ASSETS: Record<string, SanctuaryElementAsset> = {
${elements.map((e) => tsEntry(e, { key: e.iconKey, lines: [] })).join("\n")}
};

/** Zone tier-dressing layers, keyed by entry name. */
export const SANCTUARY_SCENERY_ASSETS: Record<string, SanctuarySceneryAsset> = {
${scenery.map((e) => tsEntry(e, { key: e.name, lines: [`    tierMin: ${e.tierMin},`] })).join("\n")}
};
`;

await writeFile(TS_OUT, ts);
await writeFile(
  JSON_OUT,
  JSON.stringify({ elements, scenery }, null, 2) + "\n",
);
console.log(
  `manifest: ${elements.length} element(s), ${scenery.length} scenery -> ${TS_OUT}`,
);
