// AUTO-GENERATED by scripts/sanctuary_assets/build_manifest.mjs -- DO NOT EDIT.
// Source of truth: scripts/sanctuary_assets/assets.json
// Regenerate: cd scripts/sanctuary_assets && npm run manifest

import type { SanctuaryZoneId } from "@/src/api/sanctuary";

export type SanctuaryElementAsset = {
  /** Metro asset module id (the value of require("….glb")). */
  module: number;
  zone: SanctuaryZoneId | null;
  anchor: string | null;
  scale: number;
  rotationY: number;
  animations: readonly string[];
};

export type SanctuarySceneryAsset = SanctuaryElementAsset & {
  /** Renders once the zone's depth_tier reaches this threshold. */
  tierMin: number;
};

/** Content icon key (content/sanctuary/*.json) -> placed model. */
export const SANCTUARY_ELEMENT_ASSETS: Record<string, SanctuaryElementAsset> = {

};

/** Zone tier-dressing layers, keyed by entry name. */
export const SANCTUARY_SCENERY_ASSETS: Record<string, SanctuarySceneryAsset> = {

};
