"""GCS signed-URL generation for photo upload.

Cloud Run runs under Application Default Credentials (the runtime SA), which
has no private key. V4 signed URLs are generated by delegating the actual
signing to IAM `signBlob` against the SA itself -- this requires the runtime
SA to have `roles/iam.serviceAccountTokenCreator` on itself (codified in
`infra-gcp/main.tf` as `google_service_account_iam_member.api_token_creator_self`).
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from typing import Annotated, Any, Protocol, cast

import google.auth
import google.auth.transport.requests
from fastapi import Depends, Request
from google.cloud import storage


class SignedUrlGenerator(Protocol):
    """Generates V4 signed PUT URLs for the photos bucket."""

    def generate_put_url(
        self,
        *,
        bucket: str,
        object_name: str,
        content_type: str,
        expires_in: timedelta,
    ) -> tuple[str, datetime]:
        """Return `(signed_url, expires_at)` for a single PUT.

        The URL is bound to `content_type` -- the client MUST PUT with a
        matching `Content-Type` header or the upload will be rejected.
        """
        ...


class GcsSignedUrlGenerator:
    """ADC-backed implementation. Uses IAM signBlob, no private key required."""

    def __init__(self) -> None:
        self._client = storage.Client()
        # google-auth returns a polymorphic Credentials subclass at runtime
        # (ComputeEngineCredentials on Cloud Run); the base class doesn't
        # declare service_account_email or a typed refresh, so we treat the
        # handle as Any.
        creds, _project = google.auth.default(
            scopes=["https://www.googleapis.com/auth/cloud-platform"],
        )
        self._credentials: Any = creds

    def generate_put_url(
        self,
        *,
        bucket: str,
        object_name: str,
        content_type: str,
        expires_in: timedelta,
    ) -> tuple[str, datetime]:
        # Refresh is a no-op when the cached token is still valid; on Cloud Run
        # this hits the metadata server (local + fast).
        self._credentials.refresh(google.auth.transport.requests.Request())

        bucket_obj = self._client.bucket(bucket)
        blob = bucket_obj.blob(object_name)
        url = blob.generate_signed_url(
            version="v4",
            expiration=expires_in,
            method="PUT",
            content_type=content_type,
            service_account_email=self._credentials.service_account_email,
            access_token=self._credentials.token,
        )
        expires_at = datetime.now(UTC) + expires_in
        return cast(str, url), expires_at


def get_signed_url_generator(request: Request) -> SignedUrlGenerator:
    """Pull the generator off `app.state` so tests can inject a fake."""
    generator = getattr(request.app.state, "signed_url_generator", None)
    if generator is None:
        generator = GcsSignedUrlGenerator()
        request.app.state.signed_url_generator = generator
    return cast(SignedUrlGenerator, generator)


SignedUrlGeneratorDep = Annotated[SignedUrlGenerator, Depends(get_signed_url_generator)]
