"""GCS signed-URL generation for photo upload.

Cloud Run runs under Application Default Credentials (the runtime SA), which
has no private key. V4 signed URLs are generated by delegating the actual
signing to IAM `signBlob` against the SA itself -- this requires the runtime
SA to have `roles/iam.serviceAccountTokenCreator` on itself (codified in
`infra-gcp/main.tf` as `google_service_account_iam_member.api_token_creator_self`).
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from typing import Annotated, Any, Protocol, cast

import google.auth
import google.auth.transport.requests
from fastapi import Depends, Request
from google.cloud import storage


class SignedUrlGenerator(Protocol):
    """Photo bucket facade: signed-PUT URL generation + server-side reads.

    Named `SignedUrlGenerator` for backwards compatibility with PR #30; the
    role expanded in PR #38 (Phase 7) to include `fetch_object_bytes` for
    the identify-endpoint's iNat CV call. Tests can implement either or
    both methods on a stub depending on which paths the test exercises.
    """

    def generate_put_url(
        self,
        *,
        bucket: str,
        object_name: str,
        content_type: str,
        expires_in: timedelta,
    ) -> tuple[str, datetime]:
        """Return `(signed_url, expires_at)` for a single PUT.

        The URL is bound to `content_type` -- the client MUST PUT with a
        matching `Content-Type` header or the upload will be rejected.
        """
        ...

    def fetch_object_bytes(self, *, bucket: str, object_name: str) -> bytes:
        """Read a photo's raw bytes from GCS.

        Used by the iNat identify endpoint to feed the kid's photo into
        the CV call. Server-side download keeps the iNat token off the
        mobile binary and lets us cache responses by photo_id later.
        """
        ...

    def copy_object(
        self,
        *,
        src_bucket: str,
        src_object: str,
        dst_bucket: str,
        dst_object: str,
    ) -> None:
        """Copy a GCS object server-side. Used by the moderation worker
        to move `pending/<id>.jpg` to `observations/<id>.jpg` or
        `quarantine/<id>.jpg` per ADR 0009 + `docs/moderation.md`."""
        ...

    def delete_object(self, *, bucket: str, object_name: str) -> None:
        """Delete a GCS object. Paired with `copy_object` to implement a
        move (copy then delete) on the moderation hot path."""
        ...

    def generate_get_url(
        self,
        *,
        bucket: str,
        object_name: str,
        expires_in: timedelta,
    ) -> tuple[str, datetime]:
        """Return `(signed_url, expires_at)` for a single GET.

        Used by the review-queue UI to render quarantined photos for
        teachers, and by the My Observations list to render clean photos
        for kids. Same IAM-signing pattern as `generate_put_url`.
        """
        ...


class GcsSignedUrlGenerator:
    """ADC-backed implementation. Uses IAM signBlob, no private key required."""

    def __init__(self) -> None:
        self._client = storage.Client()
        # google-auth returns a polymorphic Credentials subclass at runtime
        # (ComputeEngineCredentials on Cloud Run); the base class doesn't
        # declare service_account_email or a typed refresh, so we treat the
        # handle as Any.
        creds, _project = google.auth.default(
            scopes=["https://www.googleapis.com/auth/cloud-platform"],
        )
        self._credentials: Any = creds

    def generate_put_url(
        self,
        *,
        bucket: str,
        object_name: str,
        content_type: str,
        expires_in: timedelta,
    ) -> tuple[str, datetime]:
        # Refresh is a no-op when the cached token is still valid; on Cloud Run
        # this hits the metadata server (local + fast).
        self._credentials.refresh(google.auth.transport.requests.Request())

        bucket_obj = self._client.bucket(bucket)
        blob = bucket_obj.blob(object_name)
        url = blob.generate_signed_url(
            version="v4",
            expiration=expires_in,
            method="PUT",
            content_type=content_type,
            service_account_email=self._credentials.service_account_email,
            access_token=self._credentials.token,
        )
        expires_at = datetime.now(UTC) + expires_in
        return cast(str, url), expires_at

    def fetch_object_bytes(self, *, bucket: str, object_name: str) -> bytes:
        bucket_obj = self._client.bucket(bucket)
        blob = bucket_obj.blob(object_name)
        return cast(bytes, blob.download_as_bytes())

    def copy_object(
        self,
        *,
        src_bucket: str,
        src_object: str,
        dst_bucket: str,
        dst_object: str,
    ) -> None:
        src_bucket_obj = self._client.bucket(src_bucket)
        src_blob = src_bucket_obj.blob(src_object)
        dst_bucket_obj = self._client.bucket(dst_bucket)
        src_bucket_obj.copy_blob(src_blob, dst_bucket_obj, new_name=dst_object)

    def delete_object(self, *, bucket: str, object_name: str) -> None:
        bucket_obj = self._client.bucket(bucket)
        blob = bucket_obj.blob(object_name)
        blob.delete()

    def generate_get_url(
        self,
        *,
        bucket: str,
        object_name: str,
        expires_in: timedelta,
    ) -> tuple[str, datetime]:
        # Same metadata-server refresh pattern as generate_put_url.
        self._credentials.refresh(google.auth.transport.requests.Request())
        bucket_obj = self._client.bucket(bucket)
        blob = bucket_obj.blob(object_name)
        url = blob.generate_signed_url(
            version="v4",
            expiration=expires_in,
            method="GET",
            service_account_email=self._credentials.service_account_email,
            access_token=self._credentials.token,
        )
        expires_at = datetime.now(UTC) + expires_in
        return cast(str, url), expires_at


class BlobSignedUrlGenerator:
    """Azure Blob Storage impl using user-delegation SAS URLs.

    Container Apps managed identity must have Storage Blob Data
    Contributor on the storage account (granted in Phase 5). User
    delegation SAS is the AAD-credentialed equivalent of GCS V4 signed
    URLs -- no account key on the runtime.

    The `bucket` arg on every protocol method maps to a Blob container
    name on the configured account (single account per env, set via
    settings.blob_account_endpoint). The Protocol's `bucket` name is
    preserved for back-compat with the GCS-shaped call sites.
    """

    def __init__(self, account_endpoint: str) -> None:
        # Lazy imports so test collection doesn't require azure-storage-blob
        # when the storage_provider isn't "blob".
        from azure.identity import DefaultAzureCredential
        from azure.storage.blob import BlobServiceClient

        self._account_endpoint = account_endpoint
        self._credential = DefaultAzureCredential()
        self._service = BlobServiceClient(account_url=account_endpoint, credential=self._credential)

    def _user_delegation_key(self, lifetime: timedelta) -> Any:
        # Issue a fresh user-delegation key for each SAS mint. The key is
        # cheap to mint (one AAD call) and pinning per-request avoids
        # cross-request lifetime leaks. Later we can cache for 50min if
        # SAS minting becomes hot.
        start = datetime.now(UTC)
        return self._service.get_user_delegation_key(
            key_start_time=start,
            key_expiry_time=start + lifetime + timedelta(minutes=5),
        )

    def generate_put_url(
        self,
        *,
        bucket: str,
        object_name: str,
        content_type: str,
        expires_in: timedelta,
    ) -> tuple[str, datetime]:
        from azure.storage.blob import BlobSasPermissions, generate_blob_sas

        udk = self._user_delegation_key(expires_in)
        # parse account name out of the endpoint host
        account_name = self._account_endpoint.split("//")[1].split(".")[0]
        expires_at = datetime.now(UTC) + expires_in
        sas = generate_blob_sas(
            account_name=account_name,
            container_name=bucket,
            blob_name=object_name,
            user_delegation_key=udk,
            permission=BlobSasPermissions(write=True, create=True),
            expiry=expires_at,
            content_type=content_type,
        )
        url = f"{self._account_endpoint.rstrip('/')}/{bucket}/{object_name}?{sas}"
        return url, expires_at

    def fetch_object_bytes(self, *, bucket: str, object_name: str) -> bytes:
        blob = self._service.get_blob_client(container=bucket, blob=object_name)
        return blob.download_blob().readall()

    def copy_object(
        self,
        *,
        src_bucket: str,
        src_object: str,
        dst_bucket: str,
        dst_object: str,
    ) -> None:
        # In-account copy: pass the source blob URL with a short-lived read
        # SAS so the dst container can pull it server-side.
        from azure.storage.blob import BlobSasPermissions, generate_blob_sas

        udk = self._user_delegation_key(timedelta(minutes=5))
        account_name = self._account_endpoint.split("//")[1].split(".")[0]
        src_sas = generate_blob_sas(
            account_name=account_name,
            container_name=src_bucket,
            blob_name=src_object,
            user_delegation_key=udk,
            permission=BlobSasPermissions(read=True),
            expiry=datetime.now(UTC) + timedelta(minutes=5),
        )
        src_url = f"{self._account_endpoint.rstrip('/')}/{src_bucket}/{src_object}?{src_sas}"
        dst = self._service.get_blob_client(container=dst_bucket, blob=dst_object)
        dst.start_copy_from_url(src_url)

    def delete_object(self, *, bucket: str, object_name: str) -> None:
        blob = self._service.get_blob_client(container=bucket, blob=object_name)
        blob.delete_blob()

    def generate_get_url(
        self,
        *,
        bucket: str,
        object_name: str,
        expires_in: timedelta,
    ) -> tuple[str, datetime]:
        from azure.storage.blob import BlobSasPermissions, generate_blob_sas

        udk = self._user_delegation_key(expires_in)
        account_name = self._account_endpoint.split("//")[1].split(".")[0]
        expires_at = datetime.now(UTC) + expires_in
        sas = generate_blob_sas(
            account_name=account_name,
            container_name=bucket,
            blob_name=object_name,
            user_delegation_key=udk,
            permission=BlobSasPermissions(read=True),
            expiry=expires_at,
        )
        url = f"{self._account_endpoint.rstrip('/')}/{bucket}/{object_name}?{sas}"
        return url, expires_at


def _build_generator_for(settings: Any) -> SignedUrlGenerator:
    """Construct the configured backend. Picks GCS by default for back-compat."""
    provider = getattr(settings, "storage_provider", "gcs")
    if provider == "blob":
        endpoint = getattr(settings, "blob_account_endpoint", "")
        if not endpoint:
            raise RuntimeError("storage_provider=blob requires blob_account_endpoint to be set.")
        return BlobSignedUrlGenerator(endpoint)
    # Fall through to GCS (the legacy default through Phase 9).
    return GcsSignedUrlGenerator()


def get_signed_url_generator(request: Request) -> SignedUrlGenerator:
    """Pull the generator off `app.state` so tests can inject a fake."""
    generator = getattr(request.app.state, "signed_url_generator", None)
    if generator is None:
        settings = getattr(request.app.state, "settings", None)
        generator = _build_generator_for(settings) if settings else GcsSignedUrlGenerator()
        request.app.state.signed_url_generator = generator
    return cast(SignedUrlGenerator, generator)


SignedUrlGeneratorDep = Annotated[SignedUrlGenerator, Depends(get_signed_url_generator)]
